<form action="" class="comment-form">
    <?php if (!empty($id)) {?>
        <input type="hidden" id="<?= $id ?>">
    <?php }//if (!empty($id))?>
    <h4 class="comment-form__header">Добавить комментарий<br><br></h4>
    <div class="form-group comment-form__name-field">
        <input class="form-control" name="name" placeholder="Имя">
    </div>
    <div class="form-group comment-form__comment-field">
        <textarea class="form-control" name="comment" placeholder="Комментарий"></textarea>
    </div>
    <div class="text-right comment-form__btns">
        <input type="submit" class="btn btn-success" value="Отправить">
    </div>
</form>