<?php $comment = (array) $comment;?>
<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-lg-6">
                <?= $comment['author'] ?>
            </div>
            <div class="col-lg-6 text-right">
                <?php if (!empty($comment['children'])){ ?>
                    <b class="btn btn-primary" data-toggle="collapse" data-target="#answer_<?= $comment['id']?> ">
                        <?= count($comment['children']) ?>
                        &nbsp;<span class="glyphicon glyphicon-comment "></span>
                    </b>
                <?php }//if (!empty($comment['children'])) ?>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <?= $comment["comment"] ?>
        <hr>
        <?= \Helpers\View::make("home/comment_form", ["id" => $comment['id']]); ?>
    </div>
    <?php if (!empty($comment['children'])){ ?>
        <div class="panel-footer collapse" id="answer_<?= $comment['id']?>">
            <?php foreach ($comment['children'] as $child) {
                \Helpers\View::render("home/comment", ["comment" => $child]);
            } //foreach ($comment['children'] as $child)  ?>
        </div>
    <?php }//if (!empty($comment['children']))?>
</div>