<?php
use \Helpers\View as V;
V::extend("layouts/main");
V::startSection("content");
?>
<div class="jumbotron">
    <h1 class="text-center">Tabs or Spaces?</h1>
    <h3 class="text-center">Holywar Started !</h3>
</div>
<div class="panel panel-default" >
    <div class="panel-body" >
        <?= V::make("home/comment_form"); ?>
    </div>
</div>
<?php

foreach ($comments as $example) {
    V::render("home/comment",["comment" => $example]);
}
V::endSection("content");