<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= empty($title) ? "Title" : $title ?></title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<div class="container-fluid">
    <?= $content ?>
</div>
<script src="/js/script.js"></script>
<?php if (env("DEBUG")) {?>
<script id="__bs_script__">//<![CDATA[
    document.write("<script async src='http://HOST:3000/browser-sync/browser-sync-client.js?v=2.18.8'><\/script>".replace("HOST", location.hostname));
    //]]></script>
<?php } //if (env("DEBUG")) ?>
</body>
</html>